### ISSUE TITLE
Maintenance plans

### ISSUE THREAD

**Issue by nderscore** [nandorojo/sf-symbols-typescript#2]
The list of icons in this library is currently out of date and is missing icons from iOS 15, 16, and 17.

The original source of the icon list for this library (SFSymbols.com) is down and their [source code](https://github.com/noahsark769/SFSymbols.com) also seems unmaintained.

This issue ticket is intended to spark a discussion about maintenance plans for this library going forward.

---

I took a quick peek at Apple's official SF Symbols desktop application and was able to find plist resources containing all of the available icon names; as well as other useful metadata, such as which iOS/macOS/tvOS versions support each symbol, and which symbols are aliases of each other.

I would like to propose a rewrite of the generator scripts of this library. Instead of consuming the current JSON files from SFSymbols.com, it would instead generate typescript definitions directly from these plist files (which would be not be checked into the repository, to avoid upsetting Apple)

I'm not quite sure what (if anything) should be done with the extra icon metadata that's available. I feel like knowing which iOS (or other apple OS) version supports a certain icon is valuable information, but without being Typescript supporting JSDoc for individual string literals of a string union type, there's no straightforward way to expose this information to the developer. 😖 

The best compromise I've come up with is to make `SFSymbol` a union of string unions representing each version of SF Symbols.

```ts
/**
 * SF Symbols for iOS 13.0, macOS 10.15, tvOS 13.0, visionOS 1.0, watchOS 6.0
 */
export type SFSymbol2019 =
  | '...'
  | '...'
  
/**
 * SF Symbols for iOS 13.1, macOS 10.15, tvOS 13.0, visionOS 1.0, watchOS 6.1
 */
export type SFSymbol2019_1 =
  | SFSymbol2019
  | '...'
  | '...'
  
/**
 * SF Symbols for iOS 14.0, macOS 11.0, tvOS 14.0, visionOS 1.0, watchOS 7.0
 */
export type SFSymbol2020 =
  | SFSymbol2019_1
  | '...'
  | '...'
  
// ...

/**
 * SF Symbols for iOS 17.0, macOS 14.0, tvOS 17.0, visionOS 1.0, watchOS 10.0
 */
export type SFSymbol2023 =
  | SFSymbol2022_2
  | '...'
  | '...'

export type SFSymbol = SFSymbol2023 // expose latest version by default
```

Maybe this could be smarter and conditionally choose which version to assign to `SFSymbol` based on an interface that can be overridden by the consumer? 🤔

```ts
export interface Overrides {
  SFSymbolVersion: '2023'
};

export type SFSymbol = Overrides.SFSymbolVersion extends '2023'
  ? SFSymbol2023
  : Overrides.SFSymbolVersion extends '2022.2'
    ? SFSymbol2022_2
    : // ...
```

**Comment by nandorojo** [comment]
I think that approach makes sense.

**Comment by nandorojo** [comment]
I kinda lean towards just always updating it, and making the version of the library match the iOS version

**Comment by nandorojo** [comment]
If we did the conditional approach, each version could have its own file referenced via `import()` conditionally
